### ISSUE TITLE
add team member images in about page

### ISSUE THREAD

**Issue by oxalorg** [lambdaisland/gaiwan_co#4]

**Comment by aditya28sarin** [comment]
Hey, can you assign this issue to me, I am interested in working on this issue

**Comment by oxalorg** [comment]
Hey @aditya28sarin thanks for showing interest in this. 

This is a bit of a "chore as an issue" as it needs to deal with figuring out the css to place an image avatar somewhere near the names on this page: https://gaiwan.co/about/

If your aim is to learn Clojure we've got some good first issues over at this repo: https://github.com/lambdaisland/kaocha/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

If my assumptions are all wrong and playing with CSS is one of your favourite past times then read ahead:

- You can assume that the images are the same ratio as twitter / github profile images
- It should look decent on both mobile and desktop, but nothing crazy!
- I will pretty much accept any PR so don't fret about it :)
 
Some inspiration - here's an about page which uses those background bubbles to make it funky: https://few.io/about

**Comment by aditya28sarin** [comment]
Sure, I am interested in other issues too, I can work on this one first and then move to the others also. Can you assign me this issue?

**Comment by plexus** [comment]
Can you explain a bit more why you are interested to work on this @aditya28sarin ? Why contribute to the website of a company you are not affiliated with?

**Comment by aditya28sarin** [comment]
Sure!

I am fairly new to this domain, I am an Electrical major student who has recently moved to CS some months back and I am very excited to work on real projects, bugs issues to gain knowledge and also I find the best way to do this is to contribute back to the community. 

In this way it could help you as your issue might be completed and also help me as I could handle something new today and work on it with great passion.

**Comment by oxalorg** [comment]
@aditya28sarin Thanks, open-source needs passionate folks like you. It just feels a bit unseemly to accept   contributions as this repo is of our company site which is a for-profit entity.

But if this helps you learn something new and move ahead I would be happy to help you work on it.

Instead if you're interested, I would be extremely happy to help you get started with Open source on some of our other projects which are being used by the community! :)

**Comment by aditya28sarin** [comment]
Sure, I would love to work on any other available work you have

Aditya Sarin

**Comment by oxalorg** [comment]
@aditya28sarin Hey this is open source stuff so it's best that you find issues to contribute on to something which aligns with your interest. Can you let me know what technologies are you passionate about / want to learn?

Feel free to DM me at twitter.com/oxalorg if you want to
