### ISSUE TITLE
Change our fancy font to Cinzel

### ISSUE THREAD

**Issue by oxalorg** [lambdaisland/gaiwan_co#9]
Let's not sell our soul to Adobe and Google :)

If we stick with this, perhaps I can make a small donation to the Author: https://www.ndiscover.com/cinzel/

**Comment by plexus** [comment]
Thanks for tracking this. Seems Lubov also has some availability at the moment, maybe we should see if she can do a logo+branding package for Gaiwan.

**Comment by loopified** [comment]
As stated in #6, what @plexus mentioned is already in motion so I'm closing this. We may still be selling a tiny bit of our soul to them but not our users soul, at least. Thanks for pushing this forward @oxalorg.
